/* AUTO-GENERATED by UPDATE_PORTFOLIO.bat — do not edit manually. */
window.HM_GALLERY_DATA = {
  "version": 1,
  "selectedWork": [
    {
      "original": "images/selected-work/01_01.png",
      "thumb": "images/thumbs/selected-work/01_01.webp",
      "preview": "images/previews/selected-work/01_01.webp",
      "title": "01"
    },
    {
      "original": "images/selected-work/02_01.png",
      "thumb": "images/thumbs/selected-work/02_01.webp",
      "preview": "images/previews/selected-work/02_01.webp",
      "title": "01"
    },
    {
      "original": "images/selected-work/03_01.jpeg",
      "thumb": "images/thumbs/selected-work/03_01.webp",
      "preview": "images/previews/selected-work/03_01.webp",
      "title": "01"
    },
    {
      "original": "images/selected-work/04_0ea3fa89-b719-40a0-bd37-df663a2dc50c.png",
      "thumb": "images/thumbs/selected-work/04_0ea3fa89-b719-40a0-bd37-df663a2dc50c.webp",
      "preview": "images/previews/selected-work/04_0ea3fa89-b719-40a0-bd37-df663a2dc50c.webp",
      "title": "0ea3fa89 b719 40a0 bd37 df663a2dc50c"
    },
    {
      "original": "images/selected-work/05_Horse runing.webp",
      "thumb": "images/selected-work/05_Horse runing.webp",
      "preview": "images/selected-work/05_Horse runing.webp",
      "title": "Horse runing"
    },
    {
      "original": "images/selected-work/06_01-capsat-exhibition.jpg",
      "thumb": "images/thumbs/selected-work/06_01-capsat-exhibition.webp",
      "preview": "images/previews/selected-work/06_01-capsat-exhibition.webp",
      "title": "01 capsat exhibition"
    }
  ],
  "practice": {
    "engineering": [
      {
        "original": "images/practice/engineering/01.png",
        "thumb": "images/thumbs/practice/engineering/01.webp",
        "preview": "images/previews/practice/engineering/01.webp",
        "title": "01"
      },
      {
        "original": "images/practice/engineering/02.png",
        "thumb": "images/thumbs/practice/engineering/02.webp",
        "preview": "images/previews/practice/engineering/02.webp",
        "title": "02"
      },
      {
        "original": "images/practice/engineering/03.png",
        "thumb": "images/thumbs/practice/engineering/03.webp",
        "preview": "images/previews/practice/engineering/03.webp",
        "title": "03"
      },
      {
        "original": "images/practice/engineering/3f5a2ac9-b86d-4321-8f25-a062ff7c84f3.png",
        "thumb": "images/thumbs/practice/engineering/3f5a2ac9-b86d-4321-8f25-a062ff7c84f3.webp",
        "preview": "images/previews/practice/engineering/3f5a2ac9-b86d-4321-8f25-a062ff7c84f3.webp",
        "title": "f5a2ac9 b86d 4321 8f25 a062ff7c84f3"
      },
      {
        "original": "images/practice/engineering/3f810e12-e7d6-4ce1-b1d9-e60550adf82d.png",
        "thumb": "images/thumbs/practice/engineering/3f810e12-e7d6-4ce1-b1d9-e60550adf82d.webp",
        "preview": "images/previews/practice/engineering/3f810e12-e7d6-4ce1-b1d9-e60550adf82d.webp",
        "title": "f810e12 e7d6 4ce1 b1d9 e60550adf82d"
      },
      {
        "original": "images/practice/engineering/04.png",
        "thumb": "images/thumbs/practice/engineering/04.webp",
        "preview": "images/previews/practice/engineering/04.webp",
        "title": "04"
      },
      {
        "original": "images/practice/engineering/05.png",
        "thumb": "images/thumbs/practice/engineering/05.webp",
        "preview": "images/previews/practice/engineering/05.webp",
        "title": "05"
      },
      {
        "original": "images/practice/engineering/5cd3406b-488a-441f-a1e3-684774a4b5bb.png",
        "thumb": "images/thumbs/practice/engineering/5cd3406b-488a-441f-a1e3-684774a4b5bb.webp",
        "preview": "images/previews/practice/engineering/5cd3406b-488a-441f-a1e3-684774a4b5bb.webp",
        "title": "cd3406b 488a 441f a1e3 684774a4b5bb"
      },
      {
        "original": "images/practice/engineering/06.png",
        "thumb": "images/thumbs/practice/engineering/06.webp",
        "preview": "images/previews/practice/engineering/06.webp",
        "title": "06"
      },
      {
        "original": "images/practice/engineering/07.png",
        "thumb": "images/thumbs/practice/engineering/07.webp",
        "preview": "images/previews/practice/engineering/07.webp",
        "title": "07"
      },
      {
        "original": "images/practice/engineering/08.png",
        "thumb": "images/thumbs/practice/engineering/08.webp",
        "preview": "images/previews/practice/engineering/08.webp",
        "title": "08"
      },
      {
        "original": "images/practice/engineering/09.png",
        "thumb": "images/thumbs/practice/engineering/09.webp",
        "preview": "images/previews/practice/engineering/09.webp",
        "title": "09"
      },
      {
        "original": "images/practice/engineering/11.png",
        "thumb": "images/thumbs/practice/engineering/11.webp",
        "preview": "images/previews/practice/engineering/11.webp",
        "title": "11"
      },
      {
        "original": "images/practice/engineering/12.png",
        "thumb": "images/thumbs/practice/engineering/12.webp",
        "preview": "images/previews/practice/engineering/12.webp",
        "title": "12"
      },
      {
        "original": "images/practice/engineering/13.png",
        "thumb": "images/thumbs/practice/engineering/13.webp",
        "preview": "images/previews/practice/engineering/13.webp",
        "title": "13"
      },
      {
        "original": "images/practice/engineering/14.png",
        "thumb": "images/thumbs/practice/engineering/14.webp",
        "preview": "images/previews/practice/engineering/14.webp",
        "title": "14"
      },
      {
        "original": "images/practice/engineering/24aca280-4c20-4bbe-8ffb-ae9f9c807673.png",
        "thumb": "images/thumbs/practice/engineering/24aca280-4c20-4bbe-8ffb-ae9f9c807673.webp",
        "preview": "images/previews/practice/engineering/24aca280-4c20-4bbe-8ffb-ae9f9c807673.webp",
        "title": "aca280 4c20 4bbe 8ffb ae9f9c807673"
      },
      {
        "original": "images/practice/engineering/a_detailed_pen_and_wash_architectural_sketch_ink_d.png",
        "thumb": "images/thumbs/practice/engineering/a_detailed_pen_and_wash_architectural_sketch_ink_d.webp",
        "preview": "images/previews/practice/engineering/a_detailed_pen_and_wash_architectural_sketch_ink_d.webp",
        "title": "a detailed pen and wash architectural sketch ink d"
      },
      {
        "original": "images/practice/engineering/a_watercolor_and_ink_architectural_sketch_painting.png",
        "thumb": "images/thumbs/practice/engineering/a_watercolor_and_ink_architectural_sketch_painting.webp",
        "preview": "images/previews/practice/engineering/a_watercolor_and_ink_architectural_sketch_painting.webp",
        "title": "a watercolor and ink architectural sketch painting"
      },
      {
        "original": "images/practice/engineering/architectural_corbel_sketch_with_distant_hills.png",
        "thumb": "images/thumbs/practice/engineering/architectural_corbel_sketch_with_distant_hills.webp",
        "preview": "images/previews/practice/engineering/architectural_corbel_sketch_with_distant_hills.webp",
        "title": "architectural corbel sketch with distant hills"
      },
      {
        "original": "images/practice/engineering/architectural_sketch_of_a_mediterranean_stone_hous.png",
        "thumb": "images/thumbs/practice/engineering/architectural_sketch_of_a_mediterranean_stone_hous.webp",
        "preview": "images/previews/practice/engineering/architectural_sketch_of_a_mediterranean_stone_hous.webp",
        "title": "architectural sketch of a mediterranean stone hous"
      },
      {
        "original": "images/practice/engineering/Nohad render 01.png",
        "thumb": "images/thumbs/practice/engineering/Nohad render 01.webp",
        "preview": "images/previews/practice/engineering/Nohad render 01.webp",
        "title": "Nohad render 01"
      },
      {
        "original": "images/practice/engineering/Visualization_01.jpg",
        "thumb": "images/thumbs/practice/engineering/Visualization_01.webp",
        "preview": "images/previews/practice/engineering/Visualization_01.webp",
        "title": "Visualization 01"
      },
      {
        "original": "images/practice/engineering/Visualization_16.jpg",
        "thumb": "images/thumbs/practice/engineering/Visualization_16.webp",
        "preview": "images/previews/practice/engineering/Visualization_16.webp",
        "title": "Visualization 16"
      },
      {
        "original": "images/practice/engineering/Visualization_21.jpg",
        "thumb": "images/thumbs/practice/engineering/Visualization_21.webp",
        "preview": "images/previews/practice/engineering/Visualization_21.webp",
        "title": "Visualization 21"
      }
    ],
    "painting": [
      {
        "original": "images/practice/painting/01.png",
        "thumb": "images/thumbs/practice/painting/01.webp",
        "preview": "images/previews/practice/painting/01.webp",
        "title": "01"
      },
      {
        "original": "images/practice/painting/02.png",
        "thumb": "images/thumbs/practice/painting/02.webp",
        "preview": "images/previews/practice/painting/02.webp",
        "title": "02"
      },
      {
        "original": "images/practice/painting/03.png",
        "thumb": "images/thumbs/practice/painting/03.webp",
        "preview": "images/previews/practice/painting/03.webp",
        "title": "03"
      },
      {
        "original": "images/practice/painting/04.png",
        "thumb": "images/thumbs/practice/painting/04.webp",
        "preview": "images/previews/practice/painting/04.webp",
        "title": "04"
      },
      {
        "original": "images/practice/painting/05.png",
        "thumb": "images/thumbs/practice/painting/05.webp",
        "preview": "images/previews/practice/painting/05.webp",
        "title": "05"
      },
      {
        "original": "images/practice/painting/06.png",
        "thumb": "images/thumbs/practice/painting/06.webp",
        "preview": "images/previews/practice/painting/06.webp",
        "title": "06"
      },
      {
        "original": "images/practice/painting/07.png",
        "thumb": "images/thumbs/practice/painting/07.webp",
        "preview": "images/previews/practice/painting/07.webp",
        "title": "07"
      },
      {
        "original": "images/practice/painting/7d995226-096c-4d65-983a-4a4de07af0c3.png",
        "thumb": "images/thumbs/practice/painting/7d995226-096c-4d65-983a-4a4de07af0c3.webp",
        "preview": "images/previews/practice/painting/7d995226-096c-4d65-983a-4a4de07af0c3.webp",
        "title": "d995226 096c 4d65 983a 4a4de07af0c3"
      },
      {
        "original": "images/practice/painting/08.png",
        "thumb": "images/thumbs/practice/painting/08.webp",
        "preview": "images/previews/practice/painting/08.webp",
        "title": "08"
      },
      {
        "original": "images/practice/painting/09.png",
        "thumb": "images/thumbs/practice/painting/09.webp",
        "preview": "images/previews/practice/painting/09.webp",
        "title": "09"
      },
      {
        "original": "images/practice/painting/10.png",
        "thumb": "images/thumbs/practice/painting/10.webp",
        "preview": "images/previews/practice/painting/10.webp",
        "title": "10"
      },
      {
        "original": "images/practice/painting/11.png",
        "thumb": "images/thumbs/practice/painting/11.webp",
        "preview": "images/previews/practice/painting/11.webp",
        "title": "11"
      },
      {
        "original": "images/practice/painting/12.png",
        "thumb": "images/thumbs/practice/painting/12.webp",
        "preview": "images/previews/practice/painting/12.webp",
        "title": "12"
      },
      {
        "original": "images/practice/painting/13.png",
        "thumb": "images/thumbs/practice/painting/13.webp",
        "preview": "images/previews/practice/painting/13.webp",
        "title": "13"
      },
      {
        "original": "images/practice/painting/16.png",
        "thumb": "images/thumbs/practice/painting/16.webp",
        "preview": "images/previews/practice/painting/16.webp",
        "title": "16"
      },
      {
        "original": "images/practice/painting/an_impasto_oil_painting_palette_knife_still_life.png",
        "thumb": "images/thumbs/practice/painting/an_impasto_oil_painting_palette_knife_still_life.webp",
        "preview": "images/previews/practice/painting/an_impasto_oil_painting_palette_knife_still_life.webp",
        "title": "an impasto oil painting palette knife still life"
      },
      {
        "original": "images/practice/painting/contemplative_ink_wash_portrait.png",
        "thumb": "images/thumbs/practice/painting/contemplative_ink_wash_portrait.webp",
        "preview": "images/previews/practice/painting/contemplative_ink_wash_portrait.webp",
        "title": "contemplative ink wash portrait"
      },
      {
        "original": "images/practice/painting/warm_watercolor_portrait_of_an_elderly_man.png",
        "thumb": "images/thumbs/practice/painting/warm_watercolor_portrait_of_an_elderly_man.webp",
        "preview": "images/previews/practice/painting/warm_watercolor_portrait_of_an_elderly_man.webp",
        "title": "warm watercolor portrait of an elderly man"
      },
      {
        "original": "images/practice/painting/watercolor_portrait_of_a_bearded_scholar.png",
        "thumb": "images/thumbs/practice/painting/watercolor_portrait_of_a_bearded_scholar.webp",
        "preview": "images/previews/practice/painting/watercolor_portrait_of_a_bearded_scholar.webp",
        "title": "watercolor portrait of a bearded scholar"
      },
      {
        "original": "images/practice/painting/watercolor_portrait_of_a_smiling_girl.png",
        "thumb": "images/thumbs/practice/painting/watercolor_portrait_of_a_smiling_girl.webp",
        "preview": "images/previews/practice/painting/watercolor_portrait_of_a_smiling_girl.webp",
        "title": "watercolor portrait of a smiling girl"
      }
    ],
    "photography": [
      {
        "original": "images/practice/photography/01.jpeg",
        "thumb": "images/thumbs/practice/photography/01.webp",
        "preview": "images/previews/practice/photography/01.webp",
        "title": "01"
      },
      {
        "original": "images/practice/photography/02.jpg",
        "thumb": "images/thumbs/practice/photography/02.webp",
        "preview": "images/previews/practice/photography/02.webp",
        "title": "02"
      },
      {
        "original": "images/practice/photography/03.jpg",
        "thumb": "images/thumbs/practice/photography/03.webp",
        "preview": "images/previews/practice/photography/03.webp",
        "title": "03"
      },
      {
        "original": "images/practice/photography/04.jpg",
        "thumb": "images/thumbs/practice/photography/04.webp",
        "preview": "images/previews/practice/photography/04.webp",
        "title": "04"
      },
      {
        "original": "images/practice/photography/05.jpg",
        "thumb": "images/thumbs/practice/photography/05.webp",
        "preview": "images/previews/practice/photography/05.webp",
        "title": "05"
      },
      {
        "original": "images/practice/photography/06.jpg",
        "thumb": "images/thumbs/practice/photography/06.webp",
        "preview": "images/previews/practice/photography/06.webp",
        "title": "06"
      },
      {
        "original": "images/practice/photography/07.jpg",
        "thumb": "images/thumbs/practice/photography/07.webp",
        "preview": "images/previews/practice/photography/07.webp",
        "title": "07"
      },
      {
        "original": "images/practice/photography/08.jpg",
        "thumb": "images/thumbs/practice/photography/08.webp",
        "preview": "images/previews/practice/photography/08.webp",
        "title": "08"
      },
      {
        "original": "images/practice/photography/09.jpg",
        "thumb": "images/thumbs/practice/photography/09.webp",
        "preview": "images/previews/practice/photography/09.webp",
        "title": "09"
      },
      {
        "original": "images/practice/photography/10.jpg",
        "thumb": "images/thumbs/practice/photography/10.webp",
        "preview": "images/previews/practice/photography/10.webp",
        "title": "10"
      },
      {
        "original": "images/practice/photography/11.jpg",
        "thumb": "images/thumbs/practice/photography/11.webp",
        "preview": "images/previews/practice/photography/11.webp",
        "title": "11"
      },
      {
        "original": "images/practice/photography/12.jpg",
        "thumb": "images/thumbs/practice/photography/12.webp",
        "preview": "images/previews/practice/photography/12.webp",
        "title": "12"
      },
      {
        "original": "images/practice/photography/13.jpg",
        "thumb": "images/thumbs/practice/photography/13.webp",
        "preview": "images/previews/practice/photography/13.webp",
        "title": "13"
      },
      {
        "original": "images/practice/photography/14.jpg",
        "thumb": "images/thumbs/practice/photography/14.webp",
        "preview": "images/previews/practice/photography/14.webp",
        "title": "14"
      },
      {
        "original": "images/practice/photography/15.jpg",
        "thumb": "images/thumbs/practice/photography/15.webp",
        "preview": "images/previews/practice/photography/15.webp",
        "title": "15"
      },
      {
        "original": "images/practice/photography/16.jpeg",
        "thumb": "images/thumbs/practice/photography/16.webp",
        "preview": "images/previews/practice/photography/16.webp",
        "title": "16"
      },
      {
        "original": "images/practice/photography/17.jpeg",
        "thumb": "images/thumbs/practice/photography/17.webp",
        "preview": "images/previews/practice/photography/17.webp",
        "title": "17"
      },
      {
        "original": "images/practice/photography/18.jpeg",
        "thumb": "images/thumbs/practice/photography/18.webp",
        "preview": "images/previews/practice/photography/18.webp",
        "title": "18"
      },
      {
        "original": "images/practice/photography/19.jpeg",
        "thumb": "images/thumbs/practice/photography/19.webp",
        "preview": "images/previews/practice/photography/19.webp",
        "title": "19"
      },
      {
        "original": "images/practice/photography/20.jpeg",
        "thumb": "images/thumbs/practice/photography/20.webp",
        "preview": "images/previews/practice/photography/20.webp",
        "title": "20"
      },
      {
        "original": "images/practice/photography/21.jpeg",
        "thumb": "images/thumbs/practice/photography/21.webp",
        "preview": "images/previews/practice/photography/21.webp",
        "title": "21"
      },
      {
        "original": "images/practice/photography/22.jpeg",
        "thumb": "images/thumbs/practice/photography/22.webp",
        "preview": "images/previews/practice/photography/22.webp",
        "title": "22"
      },
      {
        "original": "images/practice/photography/23.jpeg",
        "thumb": "images/thumbs/practice/photography/23.webp",
        "preview": "images/previews/practice/photography/23.webp",
        "title": "23"
      },
      {
        "original": "images/practice/photography/24.jpeg",
        "thumb": "images/thumbs/practice/photography/24.webp",
        "preview": "images/previews/practice/photography/24.webp",
        "title": "24"
      },
      {
        "original": "images/practice/photography/25.jpeg",
        "thumb": "images/thumbs/practice/photography/25.webp",
        "preview": "images/previews/practice/photography/25.webp",
        "title": "25"
      }
    ],
    "graphic-design": [
      {
        "original": "images/practice/graphic-design/0ea3fa89-b719-40a0-bd37-df663a2dc50c.png",
        "thumb": "images/thumbs/practice/graphic-design/0ea3fa89-b719-40a0-bd37-df663a2dc50c.webp",
        "preview": "images/previews/practice/graphic-design/0ea3fa89-b719-40a0-bd37-df663a2dc50c.webp",
        "title": "ea3fa89 b719 40a0 bd37 df663a2dc50c"
      },
      {
        "original": "images/practice/graphic-design/2e50432f-e5bb-458f-94f4-30ea63fcc149.png",
        "thumb": "images/thumbs/practice/graphic-design/2e50432f-e5bb-458f-94f4-30ea63fcc149.webp",
        "preview": "images/previews/practice/graphic-design/2e50432f-e5bb-458f-94f4-30ea63fcc149.webp",
        "title": "e50432f e5bb 458f 94f4 30ea63fcc149"
      },
      {
        "original": "images/practice/graphic-design/5a34ec89-99b4-4587-a50a-4e328ceb43e7.png",
        "thumb": "images/thumbs/practice/graphic-design/5a34ec89-99b4-4587-a50a-4e328ceb43e7.webp",
        "preview": "images/previews/practice/graphic-design/5a34ec89-99b4-4587-a50a-4e328ceb43e7.webp",
        "title": "a34ec89 99b4 4587 a50a 4e328ceb43e7"
      },
      {
        "original": "images/practice/graphic-design/7f7f35d9-283f-4d39-b286-950a3d74b048.png",
        "thumb": "images/thumbs/practice/graphic-design/7f7f35d9-283f-4d39-b286-950a3d74b048.webp",
        "preview": "images/previews/practice/graphic-design/7f7f35d9-283f-4d39-b286-950a3d74b048.webp",
        "title": "f7f35d9 283f 4d39 b286 950a3d74b048"
      },
      {
        "original": "images/practice/graphic-design/256d591b-d101-47f9-bbeb-f04f6dc91558.png",
        "thumb": "images/thumbs/practice/graphic-design/256d591b-d101-47f9-bbeb-f04f6dc91558.webp",
        "preview": "images/previews/practice/graphic-design/256d591b-d101-47f9-bbeb-f04f6dc91558.webp",
        "title": "d591b d101 47f9 bbeb f04f6dc91558"
      },
      {
        "original": "images/practice/graphic-design/45212f37-cabc-4402-bf9c-3ee3c62c64fe.png",
        "thumb": "images/thumbs/practice/graphic-design/45212f37-cabc-4402-bf9c-3ee3c62c64fe.webp",
        "preview": "images/previews/practice/graphic-design/45212f37-cabc-4402-bf9c-3ee3c62c64fe.webp",
        "title": "f37 cabc 4402 bf9c 3ee3c62c64fe"
      },
      {
        "original": "images/practice/graphic-design/a_high_resolution_portrait_illustration_in_a_warm.png",
        "thumb": "images/thumbs/practice/graphic-design/a_high_resolution_portrait_illustration_in_a_warm.webp",
        "preview": "images/previews/practice/graphic-design/a_high_resolution_portrait_illustration_in_a_warm.webp",
        "title": "a high resolution portrait illustration in a warm"
      },
      {
        "original": "images/practice/graphic-design/c5cac2b0-b828-4d75-91dc-7052816545b3.png",
        "thumb": "images/thumbs/practice/graphic-design/c5cac2b0-b828-4d75-91dc-7052816545b3.webp",
        "preview": "images/previews/practice/graphic-design/c5cac2b0-b828-4d75-91dc-7052816545b3.webp",
        "title": "c5cac2b0 b828 4d75 91dc 7052816545b3"
      },
      {
        "original": "images/practice/graphic-design/d45df67a-325e-4a61-bdbd-bb0257448a5e.png",
        "thumb": "images/thumbs/practice/graphic-design/d45df67a-325e-4a61-bdbd-bb0257448a5e.webp",
        "preview": "images/previews/practice/graphic-design/d45df67a-325e-4a61-bdbd-bb0257448a5e.webp",
        "title": "d45df67a 325e 4a61 bdbd bb0257448a5e"
      },
      {
        "original": "images/practice/graphic-design/daceb9aa-ef3d-4e12-ac26-aa5bff2284ae.png",
        "thumb": "images/thumbs/practice/graphic-design/daceb9aa-ef3d-4e12-ac26-aa5bff2284ae.webp",
        "preview": "images/previews/practice/graphic-design/daceb9aa-ef3d-4e12-ac26-aa5bff2284ae.webp",
        "title": "daceb9aa ef3d 4e12 ac26 aa5bff2284ae"
      },
      {
        "original": "images/practice/graphic-design/deb2aa78-fe2d-45d0-92b0-c81708d1b608.png",
        "thumb": "images/thumbs/practice/graphic-design/deb2aa78-fe2d-45d0-92b0-c81708d1b608.webp",
        "preview": "images/previews/practice/graphic-design/deb2aa78-fe2d-45d0-92b0-c81708d1b608.webp",
        "title": "deb2aa78 fe2d 45d0 92b0 c81708d1b608"
      }
    ],
    "animation": [
      {
        "original": "images/practice/animation/1a358fc90737c667ec9d32a7c72718a8.gif",
        "thumb": "images/practice/animation/1a358fc90737c667ec9d32a7c72718a8.gif",
        "preview": "images/practice/animation/1a358fc90737c667ec9d32a7c72718a8.gif",
        "title": "a358fc90737c667ec9d32a7c72718a8"
      },
      {
        "original": "images/practice/animation/1ab0f44999aba851b67375646d4a80ce (1).gif",
        "thumb": "images/practice/animation/1ab0f44999aba851b67375646d4a80ce (1).gif",
        "preview": "images/practice/animation/1ab0f44999aba851b67375646d4a80ce (1).gif",
        "title": "ab0f44999aba851b67375646d4a80ce (1)"
      },
      {
        "original": "images/practice/animation/5e3f2e98cfb305c0ebc92c26e4764065.jpg",
        "thumb": "images/thumbs/practice/animation/5e3f2e98cfb305c0ebc92c26e4764065.webp",
        "preview": "images/previews/practice/animation/5e3f2e98cfb305c0ebc92c26e4764065.webp",
        "title": "e3f2e98cfb305c0ebc92c26e4764065"
      },
      {
        "original": "images/practice/animation/7eec78590faaea74c61d3d423b3de9ed (1).jpg",
        "thumb": "images/thumbs/practice/animation/7eec78590faaea74c61d3d423b3de9ed (1).webp",
        "preview": "images/previews/practice/animation/7eec78590faaea74c61d3d423b3de9ed (1).webp",
        "title": "eec78590faaea74c61d3d423b3de9ed (1)"
      },
      {
        "original": "images/practice/animation/57f7f8b4fe77846fc9fe48ff0e13f413.jpg",
        "thumb": "images/thumbs/practice/animation/57f7f8b4fe77846fc9fe48ff0e13f413.webp",
        "preview": "images/previews/practice/animation/57f7f8b4fe77846fc9fe48ff0e13f413.webp",
        "title": "f7f8b4fe77846fc9fe48ff0e13f413"
      },
      {
        "original": "images/practice/animation/2425899-walkcycle_side1(1).jpeg",
        "thumb": "images/thumbs/practice/animation/2425899-walkcycle_side1(1).webp",
        "preview": "images/previews/practice/animation/2425899-walkcycle_side1(1).webp",
        "title": "walkcycle side1(1)"
      },
      {
        "original": "images/practice/animation/crow-fly-sequence-black-flying-600nw-2219842119.webp",
        "thumb": "images/practice/animation/crow-fly-sequence-black-flying-600nw-2219842119.webp",
        "preview": "images/practice/animation/crow-fly-sequence-black-flying-600nw-2219842119.webp",
        "title": "crow fly sequence black flying 600nw 2219842119"
      },
      {
        "original": "images/practice/animation/d5bfb8a0fab9c1adbe9cbb90c9030a8c.jpg",
        "thumb": "images/thumbs/practice/animation/d5bfb8a0fab9c1adbe9cbb90c9030a8c.webp",
        "preview": "images/previews/practice/animation/d5bfb8a0fab9c1adbe9cbb90c9030a8c.webp",
        "title": "d5bfb8a0fab9c1adbe9cbb90c9030a8c"
      },
      {
        "original": "images/practice/animation/d48bc71dc5e169d1273fa186bfbebdfe.gif",
        "thumb": "images/practice/animation/d48bc71dc5e169d1273fa186bfbebdfe.gif",
        "preview": "images/practice/animation/d48bc71dc5e169d1273fa186bfbebdfe.gif",
        "title": "d48bc71dc5e169d1273fa186bfbebdfe"
      },
      {
        "original": "images/practice/animation/d7586a9402eade9c9ce84a10fe00490a.jpg",
        "thumb": "images/thumbs/practice/animation/d7586a9402eade9c9ce84a10fe00490a.webp",
        "preview": "images/previews/practice/animation/d7586a9402eade9c9ce84a10fe00490a.webp",
        "title": "d7586a9402eade9c9ce84a10fe00490a"
      },
      {
        "original": "images/practice/animation/dd3e5893a4611a38981b3da113cde967.jpg",
        "thumb": "images/thumbs/practice/animation/dd3e5893a4611a38981b3da113cde967.webp",
        "preview": "images/previews/practice/animation/dd3e5893a4611a38981b3da113cde967.webp",
        "title": "dd3e5893a4611a38981b3da113cde967"
      },
      {
        "original": "images/practice/animation/f7e7d248c3bfd0e2897c573dce6d3e7c.jpg",
        "thumb": "images/thumbs/practice/animation/f7e7d248c3bfd0e2897c573dce6d3e7c.webp",
        "preview": "images/previews/practice/animation/f7e7d248c3bfd0e2897c573dce6d3e7c.webp",
        "title": "f7e7d248c3bfd0e2897c573dce6d3e7c"
      },
      {
        "original": "images/practice/animation/f.jpg",
        "thumb": "images/thumbs/practice/animation/f.webp",
        "preview": "images/previews/practice/animation/f.webp",
        "title": "f"
      },
      {
        "original": "images/practice/animation/Horse runing.webp",
        "thumb": "images/practice/animation/Horse runing.webp",
        "preview": "images/practice/animation/Horse runing.webp",
        "title": "Horse runing"
      },
      {
        "original": "images/practice/animation/Hourse walk.gif",
        "thumb": "images/practice/animation/Hourse walk.gif",
        "preview": "images/practice/animation/Hourse walk.gif",
        "title": "Hourse walk"
      },
      {
        "original": "images/practice/animation/Muybridge_race_horse_animated.webp",
        "thumb": "images/practice/animation/Muybridge_race_horse_animated.webp",
        "preview": "images/practice/animation/Muybridge_race_horse_animated.webp",
        "title": "Muybridge race horse animated"
      },
      {
        "original": "images/practice/animation/richard-williams-run-cycle-copy.jpg",
        "thumb": "images/thumbs/practice/animation/richard-williams-run-cycle-copy.webp",
        "preview": "images/previews/practice/animation/richard-williams-run-cycle-copy.webp",
        "title": "richard williams run cycle copy"
      },
      {
        "original": "images/practice/animation/walk_cycle(1).jpg",
        "thumb": "images/thumbs/practice/animation/walk_cycle(1).webp",
        "preview": "images/previews/practice/animation/walk_cycle(1).webp",
        "title": "walk cycle(1)"
      }
    ],
    "training": [
      {
        "original": "images/practice/training/01-capsat-exhibition.jpg",
        "thumb": "images/thumbs/practice/training/01-capsat-exhibition.webp",
        "preview": "images/previews/practice/training/01-capsat-exhibition.webp",
        "title": "capsat exhibition"
      },
      {
        "original": "images/practice/training/02-media-exhibition.jpg",
        "thumb": "images/thumbs/practice/training/02-media-exhibition.webp",
        "preview": "images/previews/practice/training/02-media-exhibition.webp",
        "title": "media exhibition"
      },
      {
        "original": "images/practice/training/03-adms-training.jpg",
        "thumb": "images/thumbs/practice/training/03-adms-training.webp",
        "preview": "images/previews/practice/training/03-adms-training.webp",
        "title": "adms training"
      },
      {
        "original": "images/practice/training/04-adms-certificate.jpg",
        "thumb": "images/thumbs/practice/training/04-adms-certificate.webp",
        "preview": "images/previews/practice/training/04-adms-certificate.webp",
        "title": "adms certificate"
      },
      {
        "original": "images/practice/training/05-adms-group.jpg",
        "thumb": "images/thumbs/practice/training/05-adms-group.webp",
        "preview": "images/previews/practice/training/05-adms-group.webp",
        "title": "adms group"
      },
      {
        "original": "images/practice/training/06-training-2004.jpg",
        "thumb": "images/thumbs/practice/training/06-training-2004.webp",
        "preview": "images/previews/practice/training/06-training-2004.webp",
        "title": "training 2004"
      },
      {
        "original": "images/practice/training/07-training-2005.jpg",
        "thumb": "images/thumbs/practice/training/07-training-2005.webp",
        "preview": "images/previews/practice/training/07-training-2005.webp",
        "title": "training 2005"
      },
      {
        "original": "images/practice/training/08-adobe-workshop.jpg",
        "thumb": "images/thumbs/practice/training/08-adobe-workshop.webp",
        "preview": "images/previews/practice/training/08-adobe-workshop.webp",
        "title": "adobe workshop"
      },
      {
        "original": "images/practice/training/09-after-effects-class.jpg",
        "thumb": "images/thumbs/practice/training/09-after-effects-class.webp",
        "preview": "images/previews/practice/training/09-after-effects-class.webp",
        "title": "after effects class"
      },
      {
        "original": "images/practice/training/10-one-to-one-training.jpg",
        "thumb": "images/thumbs/practice/training/10-one-to-one-training.webp",
        "preview": "images/previews/practice/training/10-one-to-one-training.webp",
        "title": "one to one training"
      },
      {
        "original": "images/practice/training/11-event-demo.jpg",
        "thumb": "images/thumbs/practice/training/11-event-demo.webp",
        "preview": "images/previews/practice/training/11-event-demo.webp",
        "title": "event demo"
      },
      {
        "original": "images/practice/training/12-training-session.jpg",
        "thumb": "images/thumbs/practice/training/12-training-session.webp",
        "preview": "images/previews/practice/training/12-training-session.webp",
        "title": "training session"
      },
      {
        "original": "images/practice/training/13-aramco-training.jpg",
        "thumb": "images/thumbs/practice/training/13-aramco-training.webp",
        "preview": "images/previews/practice/training/13-aramco-training.webp",
        "title": "aramco training"
      },
      {
        "original": "images/practice/training/14-training-group-modern.jpg",
        "thumb": "images/thumbs/practice/training/14-training-group-modern.webp",
        "preview": "images/previews/practice/training/14-training-group-modern.webp",
        "title": "training group modern"
      },
      {
        "original": "images/practice/training/15-class-selfie.jpg",
        "thumb": "images/thumbs/practice/training/15-class-selfie.webp",
        "preview": "images/previews/practice/training/15-class-selfie.webp",
        "title": "class selfie"
      },
      {
        "original": "images/practice/training/16-workshop-collaboration.jpg",
        "thumb": "images/thumbs/practice/training/16-workshop-collaboration.webp",
        "preview": "images/previews/practice/training/16-workshop-collaboration.webp",
        "title": "workshop collaboration"
      },
      {
        "original": "images/practice/training/17-training-group.jpg",
        "thumb": "images/thumbs/practice/training/17-training-group.webp",
        "preview": "images/previews/practice/training/17-training-group.webp",
        "title": "training group"
      },
      {
        "original": "images/practice/training/18-lab-session.jpg",
        "thumb": "images/thumbs/practice/training/18-lab-session.webp",
        "preview": "images/previews/practice/training/18-lab-session.webp",
        "title": "lab session"
      },
      {
        "original": "images/practice/training/19-adobe-session.jpg",
        "thumb": "images/thumbs/practice/training/19-adobe-session.webp",
        "preview": "images/previews/practice/training/19-adobe-session.webp",
        "title": "adobe session"
      },
      {
        "original": "images/practice/training/IMG_0966.JPG",
        "thumb": "images/thumbs/practice/training/IMG_0966.webp",
        "preview": "images/previews/practice/training/IMG_0966.webp",
        "title": "IMG 0966"
      },
      {
        "original": "images/practice/training/IMG_0978.JPG",
        "thumb": "images/thumbs/practice/training/IMG_0978.webp",
        "preview": "images/previews/practice/training/IMG_0978.webp",
        "title": "IMG 0978"
      },
      {
        "original": "images/practice/training/IMGP8019.JPG",
        "thumb": "images/thumbs/practice/training/IMGP8019.webp",
        "preview": "images/previews/practice/training/IMGP8019.webp",
        "title": "IMGP8019"
      },
      {
        "original": "images/practice/training/IMGP8025.JPG",
        "thumb": "images/thumbs/practice/training/IMGP8025.webp",
        "preview": "images/previews/practice/training/IMGP8025.webp",
        "title": "IMGP8025"
      }
    ]
  },
  "knowledge": {
    "engineering": [
      {
        "original": "images/knowledge/engineering/images.jpeg",
        "thumb": "images/thumbs/knowledge/engineering/images.webp",
        "preview": "images/previews/knowledge/engineering/images.webp",
        "title": "images"
      }
    ],
    "painting": [],
    "photography": [
      {
        "original": "images/knowledge/photography/Fixed lighting.jpg",
        "thumb": "images/thumbs/knowledge/photography/Fixed lighting.webp",
        "preview": "images/previews/knowledge/photography/Fixed lighting.webp",
        "title": "Fixed lighting"
      },
      {
        "original": "images/knowledge/photography/Professional_HDR_Photography_Guide.png",
        "thumb": "images/thumbs/knowledge/photography/Professional_HDR_Photography_Guide.webp",
        "preview": "images/previews/knowledge/photography/Professional_HDR_Photography_Guide.webp",
        "title": "Professional HDR Photography Guide"
      }
    ],
    "graphic-design": [],
    "animation": [],
    "training": []
  }
};
