/* AUTO-GENERATED by UPDATE_PORTFOLIO.bat — do not edit manually. */
window.HM_GALLERY_DATA = {
  "version": 1,
  "selectedWork": [
    {
      "original": "images/selected-work/01_01.png",
      "thumb": "images/thumbs/selected-work/01_01.webp",
      "preview": "images/previews/selected-work/01_01.webp",
      "title": "01"
    },
    {
      "original": "images/selected-work/02_01.png",
      "thumb": "images/thumbs/selected-work/02_01.webp",
      "preview": "images/previews/selected-work/02_01.webp",
      "title": "01"
    },
    {
      "original": "images/selected-work/03_01.jpeg",
      "thumb": "images/thumbs/selected-work/03_01.webp",
      "preview": "images/previews/selected-work/03_01.webp",
      "title": "01"
    },
    {
      "original": "images/selected-work/04_0ea3fa89-b719-40a0-bd37-df663a2dc50c.png",
      "thumb": "images/thumbs/selected-work/04_0ea3fa89-b719-40a0-bd37-df663a2dc50c.webp",
      "preview": "images/previews/selected-work/04_0ea3fa89-b719-40a0-bd37-df663a2dc50c.webp",
      "title": "0ea3fa89 b719 40a0 bd37 df663a2dc50c"
    },
    {
      "original": "images/selected-work/05_Horse runing.webp",
      "thumb": "images/selected-work/05_Horse runing.webp",
      "preview": "images/selected-work/05_Horse runing.webp",
      "title": "Horse runing"
    },
    {
      "original": "images/selected-work/06_01-capsat-exhibition.jpg",
      "thumb": "images/thumbs/selected-work/06_01-capsat-exhibition.webp",
      "preview": "images/previews/selected-work/06_01-capsat-exhibition.webp",
      "title": "01 capsat exhibition"
    }
  ],
  "practice": {
    "engineering": [
      {
        "original": "images/practice/engineering/01.png",
        "thumb": "images/thumbs/practice/engineering/01.webp",
        "preview": "images/previews/practice/engineering/01.webp",
        "title": "01"
      },
      {
        "original": "images/practice/engineering/02.png",
        "thumb": "images/thumbs/practice/engineering/02.webp",
        "preview": "images/previews/practice/engineering/02.webp",
        "title": "02"
      },
      {
        "original": "images/practice/engineering/03.png",
        "thumb": "images/thumbs/practice/engineering/03.webp",
        "preview": "images/previews/practice/engineering/03.webp",
        "title": "03"
      },
      {
        "original": "images/practice/engineering/04.png",
        "thumb": "images/thumbs/practice/engineering/04.webp",
        "preview": "images/previews/practice/engineering/04.webp",
        "title": "04"
      },
      {
        "original": "images/practice/engineering/05.png",
        "thumb": "images/thumbs/practice/engineering/05.webp",
        "preview": "images/previews/practice/engineering/05.webp",
        "title": "05"
      },
      {
        "original": "images/practice/engineering/06.png",
        "thumb": "images/thumbs/practice/engineering/06.webp",
        "preview": "images/previews/practice/engineering/06.webp",
        "title": "06"
      },
      {
        "original": "images/practice/engineering/07.png",
        "thumb": "images/thumbs/practice/engineering/07.webp",
        "preview": "images/previews/practice/engineering/07.webp",
        "title": "07"
      },
      {
        "original": "images/practice/engineering/08.png",
        "thumb": "images/thumbs/practice/engineering/08.webp",
        "preview": "images/previews/practice/engineering/08.webp",
        "title": "08"
      },
      {
        "original": "images/practice/engineering/09.png",
        "thumb": "images/thumbs/practice/engineering/09.webp",
        "preview": "images/previews/practice/engineering/09.webp",
        "title": "09"
      },
      {
        "original": "images/practice/engineering/10.png",
        "thumb": "images/thumbs/practice/engineering/10.webp",
        "preview": "images/previews/practice/engineering/10.webp",
        "title": "10"
      },
      {
        "original": "images/practice/engineering/11.png",
        "thumb": "images/thumbs/practice/engineering/11.webp",
        "preview": "images/previews/practice/engineering/11.webp",
        "title": "11"
      },
      {
        "original": "images/practice/engineering/12.png",
        "thumb": "images/thumbs/practice/engineering/12.webp",
        "preview": "images/previews/practice/engineering/12.webp",
        "title": "12"
      },
      {
        "original": "images/practice/engineering/13.png",
        "thumb": "images/thumbs/practice/engineering/13.webp",
        "preview": "images/previews/practice/engineering/13.webp",
        "title": "13"
      },
      {
        "original": "images/practice/engineering/14.png",
        "thumb": "images/thumbs/practice/engineering/14.webp",
        "preview": "images/previews/practice/engineering/14.webp",
        "title": "14"
      },
      {
        "original": "images/practice/engineering/a_detailed_pen_and_wash_architectural_sketch_ink_d.png",
        "thumb": "images/thumbs/practice/engineering/a_detailed_pen_and_wash_architectural_sketch_ink_d.webp",
        "preview": "images/previews/practice/engineering/a_detailed_pen_and_wash_architectural_sketch_ink_d.webp",
        "title": "a detailed pen and wash architectural sketch ink d"
      },
      {
        "original": "images/practice/engineering/a_watercolor_and_ink_architectural_sketch_painting.png",
        "thumb": "images/thumbs/practice/engineering/a_watercolor_and_ink_architectural_sketch_painting.webp",
        "preview": "images/previews/practice/engineering/a_watercolor_and_ink_architectural_sketch_painting.webp",
        "title": "a watercolor and ink architectural sketch painting"
      },
      {
        "original": "images/practice/engineering/architectural_corbel_sketch_with_distant_hills.png",
        "thumb": "images/thumbs/practice/engineering/architectural_corbel_sketch_with_distant_hills.webp",
        "preview": "images/previews/practice/engineering/architectural_corbel_sketch_with_distant_hills.webp",
        "title": "architectural corbel sketch with distant hills"
      },
      {
        "original": "images/practice/engineering/architectural_sketch_of_a_mediterranean_stone_hous.png",
        "thumb": "images/thumbs/practice/engineering/architectural_sketch_of_a_mediterranean_stone_hous.webp",
        "preview": "images/previews/practice/engineering/architectural_sketch_of_a_mediterranean_stone_hous.webp",
        "title": "architectural sketch of a mediterranean stone hous"
      },
      {
        "original": "images/practice/engineering/mediterranean_villa_architectural_sketch.png",
        "thumb": "images/thumbs/practice/engineering/mediterranean_villa_architectural_sketch.webp",
        "preview": "images/previews/practice/engineering/mediterranean_villa_architectural_sketch.webp",
        "title": "mediterranean villa architectural sketch"
      },
      {
        "original": "images/practice/engineering/Nohad render 01.png",
        "thumb": "images/thumbs/practice/engineering/Nohad render 01.webp",
        "preview": "images/previews/practice/engineering/Nohad render 01.webp",
        "title": "Nohad render 01"
      },
      {
        "original": "images/practice/engineering/terracotta_roofed_stone_villa_sketch.png",
        "thumb": "images/thumbs/practice/engineering/terracotta_roofed_stone_villa_sketch.webp",
        "preview": "images/previews/practice/engineering/terracotta_roofed_stone_villa_sketch.webp",
        "title": "terracotta roofed stone villa sketch"
      },
      {
        "original": "images/practice/engineering/Visualization_01.jpg",
        "thumb": "images/thumbs/practice/engineering/Visualization_01.webp",
        "preview": "images/previews/practice/engineering/Visualization_01.webp",
        "title": "Visualization 01"
      },
      {
        "original": "images/practice/engineering/Visualization_16.jpg",
        "thumb": "images/thumbs/practice/engineering/Visualization_16.webp",
        "preview": "images/previews/practice/engineering/Visualization_16.webp",
        "title": "Visualization 16"
      },
      {
        "original": "images/practice/engineering/Visualization_21.jpg",
        "thumb": "images/thumbs/practice/engineering/Visualization_21.webp",
        "preview": "images/previews/practice/engineering/Visualization_21.webp",
        "title": "Visualization 21"
      }
    ],
    "painting": [
      {
        "original": "images/practice/painting/01.png",
        "thumb": "images/thumbs/practice/painting/01.webp",
        "preview": "images/previews/practice/painting/01.webp",
        "title": "01"
      },
      {
        "original": "images/practice/painting/02.png",
        "thumb": "images/thumbs/practice/painting/02.webp",
        "preview": "images/previews/practice/painting/02.webp",
        "title": "02"
      },
      {
        "original": "images/practice/painting/03.png",
        "thumb": "images/thumbs/practice/painting/03.webp",
        "preview": "images/previews/practice/painting/03.webp",
        "title": "03"
      },
      {
        "original": "images/practice/painting/04.png",
        "thumb": "images/thumbs/practice/painting/04.webp",
        "preview": "images/previews/practice/painting/04.webp",
        "title": "04"
      },
      {
        "original": "images/practice/painting/05.png",
        "thumb": "images/thumbs/practice/painting/05.webp",
        "preview": "images/previews/practice/painting/05.webp",
        "title": "05"
      },
      {
        "original": "images/practice/painting/06.png",
        "thumb": "images/thumbs/practice/painting/06.webp",
        "preview": "images/previews/practice/painting/06.webp",
        "title": "06"
      },
      {
        "original": "images/practice/painting/07.png",
        "thumb": "images/thumbs/practice/painting/07.webp",
        "preview": "images/previews/practice/painting/07.webp",
        "title": "07"
      },
      {
        "original": "images/practice/painting/08.png",
        "thumb": "images/thumbs/practice/painting/08.webp",
        "preview": "images/previews/practice/painting/08.webp",
        "title": "08"
      },
      {
        "original": "images/practice/painting/09.png",
        "thumb": "images/thumbs/practice/painting/09.webp",
        "preview": "images/previews/practice/painting/09.webp",
        "title": "09"
      },
      {
        "original": "images/practice/painting/10.png",
        "thumb": "images/thumbs/practice/painting/10.webp",
        "preview": "images/previews/practice/painting/10.webp",
        "title": "10"
      },
      {
        "original": "images/practice/painting/11.png",
        "thumb": "images/thumbs/practice/painting/11.webp",
        "preview": "images/previews/practice/painting/11.webp",
        "title": "11"
      },
      {
        "original": "images/practice/painting/12.png",
        "thumb": "images/thumbs/practice/painting/12.webp",
        "preview": "images/previews/practice/painting/12.webp",
        "title": "12"
      },
      {
        "original": "images/practice/painting/13.png",
        "thumb": "images/thumbs/practice/painting/13.webp",
        "preview": "images/previews/practice/painting/13.webp",
        "title": "13"
      },
      {
        "original": "images/practice/painting/14.png",
        "thumb": "images/thumbs/practice/painting/14.webp",
        "preview": "images/previews/practice/painting/14.webp",
        "title": "14"
      },
      {
        "original": "images/practice/painting/15.png",
        "thumb": "images/thumbs/practice/painting/15.webp",
        "preview": "images/previews/practice/painting/15.webp",
        "title": "15"
      },
      {
        "original": "images/practice/painting/16.png",
        "thumb": "images/thumbs/practice/painting/16.webp",
        "preview": "images/previews/practice/painting/16.webp",
        "title": "16"
      },
      {
        "original": "images/practice/painting/an_impasto_oil_painting_palette_knife_still_life.png",
        "thumb": "images/thumbs/practice/painting/an_impasto_oil_painting_palette_knife_still_life.webp",
        "preview": "images/previews/practice/painting/an_impasto_oil_painting_palette_knife_still_life.webp",
        "title": "an impasto oil painting palette knife still life"
      },
      {
        "original": "images/practice/painting/an_impressionistic_oil_painting_style_scene_thick.png",
        "thumb": "images/thumbs/practice/painting/an_impressionistic_oil_painting_style_scene_thick.webp",
        "preview": "images/previews/practice/painting/an_impressionistic_oil_painting_style_scene_thick.webp",
        "title": "an impressionistic oil painting style scene thick"
      },
      {
        "original": "images/practice/painting/contemplative_ink_wash_portrait.png",
        "thumb": "images/thumbs/practice/painting/contemplative_ink_wash_portrait.webp",
        "preview": "images/previews/practice/painting/contemplative_ink_wash_portrait.webp",
        "title": "contemplative ink wash portrait"
      },
      {
        "original": "images/practice/painting/dramatic_monochrome_bearded_portrait.png",
        "thumb": "images/thumbs/practice/painting/dramatic_monochrome_bearded_portrait.webp",
        "preview": "images/previews/practice/painting/dramatic_monochrome_bearded_portrait.webp",
        "title": "dramatic monochrome bearded portrait"
      },
      {
        "original": "images/practice/painting/impressionist_seaside_with_sail_tower.png",
        "thumb": "images/thumbs/practice/painting/impressionist_seaside_with_sail_tower.webp",
        "preview": "images/previews/practice/painting/impressionist_seaside_with_sail_tower.webp",
        "title": "impressionist seaside with sail tower"
      },
      {
        "original": "images/practice/painting/kindly_elder_in_impasto_oils.png",
        "thumb": "images/thumbs/practice/painting/kindly_elder_in_impasto_oils.webp",
        "preview": "images/previews/practice/painting/kindly_elder_in_impasto_oils.webp",
        "title": "kindly elder in impasto oils"
      },
      {
        "original": "images/practice/painting/warm_watercolor_portrait_of_an_elderly_man.png",
        "thumb": "images/thumbs/practice/painting/warm_watercolor_portrait_of_an_elderly_man.webp",
        "preview": "images/previews/practice/painting/warm_watercolor_portrait_of_an_elderly_man.webp",
        "title": "warm watercolor portrait of an elderly man"
      },
      {
        "original": "images/practice/painting/watercolor_portrait_of_a_bearded_scholar.png",
        "thumb": "images/thumbs/practice/painting/watercolor_portrait_of_a_bearded_scholar.webp",
        "preview": "images/previews/practice/painting/watercolor_portrait_of_a_bearded_scholar.webp",
        "title": "watercolor portrait of a bearded scholar"
      },
      {
        "original": "images/practice/painting/watercolor_portrait_of_a_smiling_girl.png",
        "thumb": "images/thumbs/practice/painting/watercolor_portrait_of_a_smiling_girl.webp",
        "preview": "images/previews/practice/painting/watercolor_portrait_of_a_smiling_girl.webp",
        "title": "watercolor portrait of a smiling girl"
      }
    ],
    "photography": [
      {
        "original": "images/practice/photography/01.jpeg",
        "thumb": "images/thumbs/practice/photography/01.webp",
        "preview": "images/previews/practice/photography/01.webp",
        "title": "01"
      },
      {
        "original": "images/practice/photography/02.jpg",
        "thumb": "images/thumbs/practice/photography/02.webp",
        "preview": "images/previews/practice/photography/02.webp",
        "title": "02"
      },
      {
        "original": "images/practice/photography/03.jpg",
        "thumb": "images/thumbs/practice/photography/03.webp",
        "preview": "images/previews/practice/photography/03.webp",
        "title": "03"
      },
      {
        "original": "images/practice/photography/04.jpg",
        "thumb": "images/thumbs/practice/photography/04.webp",
        "preview": "images/previews/practice/photography/04.webp",
        "title": "04"
      },
      {
        "original": "images/practice/photography/05.jpg",
        "thumb": "images/thumbs/practice/photography/05.webp",
        "preview": "images/previews/practice/photography/05.webp",
        "title": "05"
      },
      {
        "original": "images/practice/photography/06.jpg",
        "thumb": "images/thumbs/practice/photography/06.webp",
        "preview": "images/previews/practice/photography/06.webp",
        "title": "06"
      },
      {
        "original": "images/practice/photography/07.jpg",
        "thumb": "images/thumbs/practice/photography/07.webp",
        "preview": "images/previews/practice/photography/07.webp",
        "title": "07"
      },
      {
        "original": "images/practice/photography/08.jpg",
        "thumb": "images/thumbs/practice/photography/08.webp",
        "preview": "images/previews/practice/photography/08.webp",
        "title": "08"
      },
      {
        "original": "images/practice/photography/09.jpg",
        "thumb": "images/thumbs/practice/photography/09.webp",
        "preview": "images/previews/practice/photography/09.webp",
        "title": "09"
      },
      {
        "original": "images/practice/photography/10.jpg",
        "thumb": "images/thumbs/practice/photography/10.webp",
        "preview": "images/previews/practice/photography/10.webp",
        "title": "10"
      },
      {
        "original": "images/practice/photography/11.jpg",
        "thumb": "images/thumbs/practice/photography/11.webp",
        "preview": "images/previews/practice/photography/11.webp",
        "title": "11"
      },
      {
        "original": "images/practice/photography/12.jpg",
        "thumb": "images/thumbs/practice/photography/12.webp",
        "preview": "images/previews/practice/photography/12.webp",
        "title": "12"
      },
      {
        "original": "images/practice/photography/13.jpg",
        "thumb": "images/thumbs/practice/photography/13.webp",
        "preview": "images/previews/practice/photography/13.webp",
        "title": "13"
      },
      {
        "original": "images/practice/photography/14.jpg",
        "thumb": "images/thumbs/practice/photography/14.webp",
        "preview": "images/previews/practice/photography/14.webp",
        "title": "14"
      },
      {
        "original": "images/practice/photography/15.jpg",
        "thumb": "images/thumbs/practice/photography/15.webp",
        "preview": "images/previews/practice/photography/15.webp",
        "title": "15"
      },
      {
        "original": "images/practice/photography/16.jpeg",
        "thumb": "images/thumbs/practice/photography/16.webp",
        "preview": "images/previews/practice/photography/16.webp",
        "title": "16"
      },
      {
        "original": "images/practice/photography/17.jpeg",
        "thumb": "images/thumbs/practice/photography/17.webp",
        "preview": "images/previews/practice/photography/17.webp",
        "title": "17"
      },
      {
        "original": "images/practice/photography/18.jpeg",
        "thumb": "images/thumbs/practice/photography/18.webp",
        "preview": "images/previews/practice/photography/18.webp",
        "title": "18"
      },
      {
        "original": "images/practice/photography/19.jpeg",
        "thumb": "images/thumbs/practice/photography/19.webp",
        "preview": "images/previews/practice/photography/19.webp",
        "title": "19"
      },
      {
        "original": "images/practice/photography/20.jpeg",
        "thumb": "images/thumbs/practice/photography/20.webp",
        "preview": "images/previews/practice/photography/20.webp",
        "title": "20"
      },
      {
        "original": "images/practice/photography/21.jpeg",
        "thumb": "images/thumbs/practice/photography/21.webp",
        "preview": "images/previews/practice/photography/21.webp",
        "title": "21"
      },
      {
        "original": "images/practice/photography/22.jpeg",
        "thumb": "images/thumbs/practice/photography/22.webp",
        "preview": "images/previews/practice/photography/22.webp",
        "title": "22"
      },
      {
        "original": "images/practice/photography/23.jpeg",
        "thumb": "images/thumbs/practice/photography/23.webp",
        "preview": "images/previews/practice/photography/23.webp",
        "title": "23"
      },
      {
        "original": "images/practice/photography/24.jpeg",
        "thumb": "images/thumbs/practice/photography/24.webp",
        "preview": "images/previews/practice/photography/24.webp",
        "title": "24"
      },
      {
        "original": "images/practice/photography/25.jpeg",
        "thumb": "images/thumbs/practice/photography/25.webp",
        "preview": "images/previews/practice/photography/25.webp",
        "title": "25"
      }
    ],
    "graphic-design": [
      {
        "original": "images/practice/graphic-design/0ea3fa89-b719-40a0-bd37-df663a2dc50c.png",
        "thumb": "images/thumbs/practice/graphic-design/0ea3fa89-b719-40a0-bd37-df663a2dc50c.webp",
        "preview": "images/previews/practice/graphic-design/0ea3fa89-b719-40a0-bd37-df663a2dc50c.webp",
        "title": "ea3fa89 b719 40a0 bd37 df663a2dc50c"
      },
      {
        "original": "images/practice/graphic-design/733c36aa-bfff-4081-8a8a-310a2c846985.png",
        "thumb": "images/thumbs/practice/graphic-design/733c36aa-bfff-4081-8a8a-310a2c846985.webp",
        "preview": "images/previews/practice/graphic-design/733c36aa-bfff-4081-8a8a-310a2c846985.webp",
        "title": "c36aa bfff 4081 8a8a 310a2c846985"
      },
      {
        "original": "images/practice/graphic-design/26594ad7-fa53-41e9-a4a7-b913fc515e30.png",
        "thumb": "images/thumbs/practice/graphic-design/26594ad7-fa53-41e9-a4a7-b913fc515e30.webp",
        "preview": "images/previews/practice/graphic-design/26594ad7-fa53-41e9-a4a7-b913fc515e30.webp",
        "title": "ad7 fa53 41e9 a4a7 b913fc515e30"
      },
      {
        "original": "images/practice/graphic-design/a_high_resolution_portrait_illustration_in_a_warm.png",
        "thumb": "images/thumbs/practice/graphic-design/a_high_resolution_portrait_illustration_in_a_warm.webp",
        "preview": "images/previews/practice/graphic-design/a_high_resolution_portrait_illustration_in_a_warm.webp",
        "title": "a high resolution portrait illustration in a warm"
      },
      {
        "original": "images/practice/graphic-design/cc637936-32c3-4ac1-939a-7ad2967c8ea8.png",
        "thumb": "images/thumbs/practice/graphic-design/cc637936-32c3-4ac1-939a-7ad2967c8ea8.webp",
        "preview": "images/previews/practice/graphic-design/cc637936-32c3-4ac1-939a-7ad2967c8ea8.webp",
        "title": "cc637936 32c3 4ac1 939a 7ad2967c8ea8"
      },
      {
        "original": "images/practice/graphic-design/d45df67a-325e-4a61-bdbd-bb0257448a5e.png",
        "thumb": "images/thumbs/practice/graphic-design/d45df67a-325e-4a61-bdbd-bb0257448a5e.webp",
        "preview": "images/previews/practice/graphic-design/d45df67a-325e-4a61-bdbd-bb0257448a5e.webp",
        "title": "d45df67a 325e 4a61 bdbd bb0257448a5e"
      }
    ],
    "animation": [
      {
        "original": "images/practice/animation/01.svg",
        "thumb": "images/practice/animation/01.svg",
        "preview": "images/practice/animation/01.svg",
        "title": "01"
      },
      {
        "original": "images/practice/animation/02.svg",
        "thumb": "images/practice/animation/02.svg",
        "preview": "images/practice/animation/02.svg",
        "title": "02"
      },
      {
        "original": "images/practice/animation/03.svg",
        "thumb": "images/practice/animation/03.svg",
        "preview": "images/practice/animation/03.svg",
        "title": "03"
      },
      {
        "original": "images/practice/animation/04.svg",
        "thumb": "images/practice/animation/04.svg",
        "preview": "images/practice/animation/04.svg",
        "title": "04"
      },
      {
        "original": "images/practice/animation/05.svg",
        "thumb": "images/practice/animation/05.svg",
        "preview": "images/practice/animation/05.svg",
        "title": "05"
      },
      {
        "original": "images/practice/animation/06.svg",
        "thumb": "images/practice/animation/06.svg",
        "preview": "images/practice/animation/06.svg",
        "title": "06"
      },
      {
        "original": "images/practice/animation/07.svg",
        "thumb": "images/practice/animation/07.svg",
        "preview": "images/practice/animation/07.svg",
        "title": "07"
      },
      {
        "original": "images/practice/animation/08.svg",
        "thumb": "images/practice/animation/08.svg",
        "preview": "images/practice/animation/08.svg",
        "title": "08"
      },
      {
        "original": "images/practice/animation/09.svg",
        "thumb": "images/practice/animation/09.svg",
        "preview": "images/practice/animation/09.svg",
        "title": "09"
      },
      {
        "original": "images/practice/animation/10.svg",
        "thumb": "images/practice/animation/10.svg",
        "preview": "images/practice/animation/10.svg",
        "title": "10"
      },
      {
        "original": "images/practice/animation/11.svg",
        "thumb": "images/practice/animation/11.svg",
        "preview": "images/practice/animation/11.svg",
        "title": "11"
      },
      {
        "original": "images/practice/animation/12.svg",
        "thumb": "images/practice/animation/12.svg",
        "preview": "images/practice/animation/12.svg",
        "title": "12"
      },
      {
        "original": "images/practice/animation/2425899-walkcycle_side1(1).jpeg",
        "thumb": "images/thumbs/practice/animation/2425899-walkcycle_side1(1).webp",
        "preview": "images/previews/practice/animation/2425899-walkcycle_side1(1).webp",
        "title": "walkcycle side1(1)"
      },
      {
        "original": "images/practice/animation/Horse runing.webp",
        "thumb": "images/practice/animation/Horse runing.webp",
        "preview": "images/practice/animation/Horse runing.webp",
        "title": "Horse runing"
      },
      {
        "original": "images/practice/animation/Hourse walk.gif",
        "thumb": "images/practice/animation/Hourse walk.gif",
        "preview": "images/practice/animation/Hourse walk.gif",
        "title": "Hourse walk"
      },
      {
        "original": "images/practice/animation/Jump(1).png",
        "thumb": "images/thumbs/practice/animation/Jump(1).webp",
        "preview": "images/previews/practice/animation/Jump(1).webp",
        "title": "Jump(1)"
      },
      {
        "original": "images/practice/animation/richard-williams-run-cycle-copy.jpg",
        "thumb": "images/thumbs/practice/animation/richard-williams-run-cycle-copy.webp",
        "preview": "images/previews/practice/animation/richard-williams-run-cycle-copy.webp",
        "title": "richard williams run cycle copy"
      },
      {
        "original": "images/practice/animation/walk_cycle(1).jpg",
        "thumb": "images/thumbs/practice/animation/walk_cycle(1).webp",
        "preview": "images/previews/practice/animation/walk_cycle(1).webp",
        "title": "walk cycle(1)"
      }
    ],
    "training": [
      {
        "original": "images/practice/training/01-capsat-exhibition.jpg",
        "thumb": "images/thumbs/practice/training/01-capsat-exhibition.webp",
        "preview": "images/previews/practice/training/01-capsat-exhibition.webp",
        "title": "capsat exhibition"
      },
      {
        "original": "images/practice/training/02-media-exhibition.jpg",
        "thumb": "images/thumbs/practice/training/02-media-exhibition.webp",
        "preview": "images/previews/practice/training/02-media-exhibition.webp",
        "title": "media exhibition"
      },
      {
        "original": "images/practice/training/03-adms-training.jpg",
        "thumb": "images/thumbs/practice/training/03-adms-training.webp",
        "preview": "images/previews/practice/training/03-adms-training.webp",
        "title": "adms training"
      },
      {
        "original": "images/practice/training/04-adms-certificate.jpg",
        "thumb": "images/thumbs/practice/training/04-adms-certificate.webp",
        "preview": "images/previews/practice/training/04-adms-certificate.webp",
        "title": "adms certificate"
      },
      {
        "original": "images/practice/training/05-adms-group.jpg",
        "thumb": "images/thumbs/practice/training/05-adms-group.webp",
        "preview": "images/previews/practice/training/05-adms-group.webp",
        "title": "adms group"
      },
      {
        "original": "images/practice/training/06-training-2004.jpg",
        "thumb": "images/thumbs/practice/training/06-training-2004.webp",
        "preview": "images/previews/practice/training/06-training-2004.webp",
        "title": "training 2004"
      },
      {
        "original": "images/practice/training/07-training-2005.jpg",
        "thumb": "images/thumbs/practice/training/07-training-2005.webp",
        "preview": "images/previews/practice/training/07-training-2005.webp",
        "title": "training 2005"
      },
      {
        "original": "images/practice/training/08-adobe-workshop.jpg",
        "thumb": "images/thumbs/practice/training/08-adobe-workshop.webp",
        "preview": "images/previews/practice/training/08-adobe-workshop.webp",
        "title": "adobe workshop"
      },
      {
        "original": "images/practice/training/09-after-effects-class.jpg",
        "thumb": "images/thumbs/practice/training/09-after-effects-class.webp",
        "preview": "images/previews/practice/training/09-after-effects-class.webp",
        "title": "after effects class"
      },
      {
        "original": "images/practice/training/10-one-to-one-training.jpg",
        "thumb": "images/thumbs/practice/training/10-one-to-one-training.webp",
        "preview": "images/previews/practice/training/10-one-to-one-training.webp",
        "title": "one to one training"
      },
      {
        "original": "images/practice/training/11-event-demo.jpg",
        "thumb": "images/thumbs/practice/training/11-event-demo.webp",
        "preview": "images/previews/practice/training/11-event-demo.webp",
        "title": "event demo"
      },
      {
        "original": "images/practice/training/12-training-session.jpg",
        "thumb": "images/thumbs/practice/training/12-training-session.webp",
        "preview": "images/previews/practice/training/12-training-session.webp",
        "title": "training session"
      },
      {
        "original": "images/practice/training/13-aramco-training.jpg",
        "thumb": "images/thumbs/practice/training/13-aramco-training.webp",
        "preview": "images/previews/practice/training/13-aramco-training.webp",
        "title": "aramco training"
      },
      {
        "original": "images/practice/training/14-training-group-modern.jpg",
        "thumb": "images/thumbs/practice/training/14-training-group-modern.webp",
        "preview": "images/previews/practice/training/14-training-group-modern.webp",
        "title": "training group modern"
      },
      {
        "original": "images/practice/training/15-class-selfie.jpg",
        "thumb": "images/thumbs/practice/training/15-class-selfie.webp",
        "preview": "images/previews/practice/training/15-class-selfie.webp",
        "title": "class selfie"
      },
      {
        "original": "images/practice/training/16-workshop-collaboration.jpg",
        "thumb": "images/thumbs/practice/training/16-workshop-collaboration.webp",
        "preview": "images/previews/practice/training/16-workshop-collaboration.webp",
        "title": "workshop collaboration"
      },
      {
        "original": "images/practice/training/17-training-group.jpg",
        "thumb": "images/thumbs/practice/training/17-training-group.webp",
        "preview": "images/previews/practice/training/17-training-group.webp",
        "title": "training group"
      },
      {
        "original": "images/practice/training/18-lab-session.jpg",
        "thumb": "images/thumbs/practice/training/18-lab-session.webp",
        "preview": "images/previews/practice/training/18-lab-session.webp",
        "title": "lab session"
      },
      {
        "original": "images/practice/training/19-adobe-session.jpg",
        "thumb": "images/thumbs/practice/training/19-adobe-session.webp",
        "preview": "images/previews/practice/training/19-adobe-session.webp",
        "title": "adobe session"
      }
    ]
  },
  "knowledge": {
    "engineering": [
      {
        "original": "images/knowledge/engineering/images.jpeg",
        "thumb": "images/thumbs/knowledge/engineering/images.webp",
        "preview": "images/previews/knowledge/engineering/images.webp",
        "title": "images"
      }
    ],
    "painting": [],
    "photography": [
      {
        "original": "images/knowledge/photography/Fixed lighting.jpg",
        "thumb": "images/thumbs/knowledge/photography/Fixed lighting.webp",
        "preview": "images/previews/knowledge/photography/Fixed lighting.webp",
        "title": "Fixed lighting"
      },
      {
        "original": "images/knowledge/photography/Professional_HDR_Photography_Guide.png",
        "thumb": "images/thumbs/knowledge/photography/Professional_HDR_Photography_Guide.webp",
        "preview": "images/previews/knowledge/photography/Professional_HDR_Photography_Guide.webp",
        "title": "Professional HDR Photography Guide"
      }
    ],
    "graphic-design": [],
    "animation": [],
    "training": []
  }
};
